=== SoyManoolo/M04-LenguajeMarcas/NF01/examen xsd/MUSIC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="https://elpuig.xeill.net/MP04/XSD"
           targetNamespace="https://elpuig.xeill.net/MP04/XSD" 
           elementFormDefault="qualified">

    <xs:element name="MUSIC"> <!-- Declarem l'element arrel-->
        <xs:complexType>
            <xs:sequence> <!-- Dins de sequence declarem els elements fills de MUSIC-->
                <xs:element name="EXTENDED" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence> <!-- Dins de sequence declarem els elements fills d'EXTENDED i el seu tipus-->
                            <xs:element name="TITLE" type="xs:string"/> <!-- Es de tipus xs:string perque el titol pot variar-->
                            <xs:element name="ARTIST" type="xs:string"/> <!-- Es de tipus xs:string perque l'artista varia-->
                            <xs:element name="COMPANY" type="xs:string"/> <!-- Es de tipus xs:string perque la companyia varia-->
                            <xs:element name="YEAR" type="xs:integer"/> <!-- Es de tipus xs:integer perque l'any pot variar-->
                        </xs:sequence>
                        <xs:attribute name="plataform" type="xs:string"/> <!-- Declarem l'atribut plataform dins de l'etiqueta EXTENDED amb tipus xs:string perque hi ha diferents tipus de plataforma-->
                    </xs:complexType>
                </xs:element>
                <xs:element name="LONG" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TITLE" type="xs:string"/>
                            <xs:element name="ARTIST" type="xs:string"/>
                            <xs:element name="COMPANY" type="xs:string"/>
                            <xs:element name="YEAR" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="plataform" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SoyManoolo/M04-LenguajeMarcas/NF01/examen xsd/MUSIC.xml
<?xml version="1.0" encoding="UTF-8"?>
<MUSIC xmlns="https://elpuig.xeill.net/MP04/XSD"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://elpuig.xeill.net/MP04/XSD MUSIC.xsd">

    <MUSIC>
        <EXTENDED plataform="CD">
            <TITLE>Nobody's Journey</TITLE>
            <ARTIST>Nolah</ARTIST>
            <COMPANY>Click Records</COMPANY>
            <YEAR>2017</YEAR>
        </EXTENDED>
        <LONG plataform="MP3">
            <TITLE>Hide your heart</TITLE>
            <ARTIST>Bonnie Tayler</ARTIST>
            <COMPANY>CBS Records</COMPANY>
            <YEAR>1988</YEAR>
        </LONG>
        <LONG plataform="streaming">
            <TITLE>Greatest Hits</TITLE>
            <ARTIST>Dolly Parton</ARTIST>
            <COMPANY>RCA</COMPANY>
            <YEAR>1982</YEAR>
        </LONG>
    </MUSIC>
</MUSIC>
