=== SoyManoolo/M04-LenguajeMarcas/NF01/examen dtd/GAMES.dtd
<!ELEMENT GAMES (BOARDGAME*, VIDEOGAME*)> <!-- Declarem l'element arrel i els seus fills-->
<!ELEMENT BOARDGAME (TITLE, GENERE, DESIGNER, YEAR)> <!-- Declarem les etiquetes fill de BOARDGAME-->
<!ELEMENT TITLE (#PCDATA)> <!-- Declarem el tipus d'iformació #PCDATA dins de TITLE perquè trobem una cadena de text i aquest pot variar depenent del BOARDGAME-->
<!ELEMENT GENERE (#PCDATA)> <!-- Declarem el tipus d'iformació #PCDATA dins de GENERE perquè hi ha diferents tipus de genere als jocs-->
<!ELEMENT DESIGNER (#PCDATA)> <!-- Declarem el tipus d'iformació #PCDATA dins de DESIGNER perquè pot ser un diferent disenyador el que hagi fet el joc-->
<!ELEMENT YEAR (#PCDATA)> <!-- Declarem el tipus d'iformació #PCDATA dins de YEAR perquè l'any de creació del joc pot variar-->
<!ELEMENT VIDEOGAME (TITLE, GENERE, DESIGNER, YEAR)> <!-- Declarem les etiquetes fill de VIDEOGAME-->
<!ATTLIST BOARDGAME maxplayers CDATA #REQUIRED> <!-- Declarem l'atribut maxplayers dins l'etiqueta BOARDGAME i el tipus de dada CDATA perquè la quantitat màxima de jugadors pot variar -->
<!ATTLIST VIDEOGAME maxplayers CDATA #REQUIRED>

=== SoyManoolo/M04-LenguajeMarcas/NF01/examen dtd/GAMES.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GAMES SYSTEM "GAMES.dtd">
<GAMES>
    <BOARDGAME maxplayers="8">
        <TITLE>Risk</TITLE>
        <GENERE>strategy</GENERE>
        <DESIGNER>Albert Lammorisse</DESIGNER>
        <YEAR>1958</YEAR>
    </BOARDGAME>
    <VIDEOGAME maxplayers="1">
        <TITLE>Xenoblade Chronicles 2</TITLE>
        <GENERE>ROL</GENERE>
        <DESIGNER>Koji Hayashi</DESIGNER>
        <YEAR>2017</YEAR>
    </VIDEOGAME>
    <VIDEOGAME maxplayers="4">
        <TITLE>Contra</TITLE>
        <GENERE>Run and Gun</GENERE>
        <DESIGNER>Koji Hiroshita</DESIGNER>
        <YEAR>1987</YEAR>
    </VIDEOGAME>
</GAMES>
